### ISSUE TITLE
Question: how are broken connections handled by the pool?

### ISSUE THREAD

**Issue by crontab** [vapor/mysql-kit#306]
Let's say for whatever reason the MySQL server drops a connection with the client, while it is in the pool on the SwiftNIO side. Some SwiftNIO handler requests a connection from the pool and gets a non-functioning connection that will likely return an error pretty soon. How are this type of situations handled by mysql-kit  (or the underlying mysql-nio module)?

In other words, how are connections kept alive and guaranteed to function properly when pulled from the pool? And same for the UNIX domain sockets, too.

Thanks!

**Comment by 0xTim** [comment]
I believe this was solved [on the forums](https://forums.swift.org/t/how-do-connection-pools-handle-broken-connections/57111). Feel free to reopen if there are still unanswered questions!

**Comment by crontab** [comment]
> I believe this was solved [on the forums](https://forums.swift.org/t/how-do-connection-pools-handle-broken-connections/57111). Feel free to reopen if there are still unanswered questions!

Unfortunately it wasn't solved, though some minimal discussion did take place there. 

Plus my question was quite specific: does MySQLKit have any keep-alive mechanisms in place that would make the connection pool more reliable? I know I should probably study the MySQLNIO sources and find out myself, I just thought someone already knows.

**Comment by 0xTim** [comment]
No MySQLKit uses AsyncKit's [ConnectionPool](https://github.com/vapor/async-kit/tree/main/Sources/AsyncKit/ConnectionPool) which has no concept of a keep alive, so I believe MySQL does nothing for this. cc @gwynne
